[application]
name = "Arto"
default_platform = "desktop"

[bundle]
identifier = "com.lambdalisue.Arto"
publisher = "lambdalisue"
icon = ["../extras/mac/arto-app.icns"]
copyright = "Copyright 2025 lambdalisue"
category = "Utility"
short_description = "A GitHub Markdown viewer"
long_description = """
Arto is a GitHub Markdown viewer built with Dioxus.
"""

[bundle.macos]
license = "../LICENSE"
provider_short_name = "Alisue"
info_plist_path = "../extras/mac/Info.plist"
files = {}
hardened_runtime = false # because we don't have a proper Apple Developer ID
signing_identity = "-" # use ad-hoc signing for ARM64 compatibility
